FROM php:8.2-fpm-alpine 

# 安装系统依赖
RUN apk add --no-cache \
    libpng-dev \
    libjpeg-turbo-dev \
    libwebp-dev \
    libzip-dev \
	linux-headers \
    icu-dev \
	postgresql-dev \
	curl \
	git \
	unzip \
    $PHPIZE_DEPS

# 安装核心扩展
RUN docker-php-ext-configure gd --with-jpeg --with-webp \
    && docker-php-ext-install -j$(nproc) \
        pdo_mysql \
        pdo_pgsql \
        gd \
        zip \
        intl \
		bcmath \
		exif \
		pcntl \
		opcache \
		sockets 

# 通过环境变量覆盖配置
ENV PHP_OPCACHE_ENABLE=0 \
    PHP_OPCACHE_ENABLE_CLI=0
# 安装 Xdebug（开发环境）


RUN pecl install redis-5.3.7 \
    && docker-php-ext-enable redis
	
# 安装 Composer（验证签名版）
RUN curl -sS https://getcomposer.org/installer | php -- \
    --install-dir=/usr/local/bin \
    --filename=composer \
    --version=2.6.6 \
    --quiet \
    && composer --ansi --version --no-interaction

# 验证安装
RUN composer diagnose

# 生产环境优化
RUN echo "opcache.enable=1" >> /usr/local/etc/php/conf.d/opcache.ini \
    && echo "opcache.validate_timestamps=0" >> /usr/local/etc/php/conf.d/opcache.ini

# 清理缓存
RUN rm -rf /tmp/pear \
    && apk del $PHPIZE_DEPS
	
WORKDIR /var/www/html